<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.kroger.pharmacy.csr</groupId>
	<artifactId>csrwebmanager-parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>CSR Web Manager Parent</name>
	<description>Controlled Substance Reporting Web Manager</description>

	<properties>
        <java.version>1.8</java.version>
        <build.agent>NONE</build.agent>
        <build.number>UNKNOWN</build.number>
	</properties>

	<modules>
		<module>csr</module>
	</modules>
</project>