#PingOne Configurations	- stage
pingone.authorize_endpoint=https://auth.pingone.com/6c0241eb-6d4c-4b98-bdfb-5ab44b0d7112/as/authorize
pingone.token_endpoint=https://auth.pingone.com/6c0241eb-6d4c-4b98-bdfb-5ab44b0d7112/as/token
pingone.client_id=72de9418-c4b5-4aba-9243-c3e085817b25
pingone.client_secret=45Pqh0uMGkta3sdoa8lSTdCQzvdtf6N75rJppbPRwBeAMEFb8~R4FA6kzeKZ~rzK
pingone.logout_endpoint=https://auth.pingone.com/6c0241eb-6d4c-4b98-bdfb-5ab44b0d7112/as/signoff
