#PingOne Configuration - prod
pingone.client_id  = 4ad92fc1-2bb7-45e9-9b1e-89e657c3cbeb
pingone.client_secret = nQt9cBoLzhnmYPqRLzautj0OTmjh0rKpGR4yUir5BorQW8IYPhFnr17iuwv7aW0K
pingone.token_endpoint = https://auth.pingone.com/1b93dc23-a27b-4a7d-b0eb-c55c0c10e862/as/token
pingone.authorize_endpoint  = https://auth.pingone.com/1b93dc23-a27b-4a7d-b0eb-c55c0c10e862/as/authorize
pingone.logout_endpoint= https://auth.pingone.com/1b93dc23-a27b-4a7d-b0eb-c55c0c10e862/as/signoff
