# Tracking Users. If this attribute is set to true, then the
# user details are added to a map which can be accessed by the
# application. A SessionListener should enabled to remove
# user from the map.
trackUsers=true

# This file implements a way for developers to login to Applications when it is
# running on their own machine.  This is necessary since SiteMinder, which
# normally implements the login challenge, cannot run on developers' personal
# workstations.  

# This field must be set to the ip addresses of the developers' workstations.  
# Please do not check in this file with an IP Address set to anything other than a 
# test machine.  This implements a safeguard that helps assure a true 
# SiteMinder login can never be bypassed in production.
# Use a comma separated list of addresses.
#
# NEVER SET THE PRODUCTION SERVER'S IP ADDRESS HERE!
#
ipAddressesAllowingSpoofing=10.252.18.42,\
10.130.1.196,\
192.168.1.100,\
192.168.1.102,\
127.0.0.1,\
0.0.0.0

# The above IP Addresses are in the following order
# Home Router addresses
# Local addresses
# No address


# The following blocks represent "profiles" (i.e., userids) developers can use to
# login when running Applications on their own development workstation.  The profile
# the developer will use is the first dot-delimited token on the left side
# within each block (e.g., for the appdev example below, the developer could 
# login using the code "appdev").

# This block mimicks an eDirectory LDAP server userid.  The following values are
# the header variables SiteMinder will pass to the application when authentication is 
# successful against the eDirectory LDAP server.
# All variables are all required.
#
APPDEV.roles                     =CN=sm-eprndw-csradmin
APPDEV.division                  =060
APPDEV.location                  =00 00000
APPDEV.fullname                  =csr Team
APPDEV.firstname                 =csr
APPDEV.lastname                  =Team
APPDEV.jobcode                   =12345

SUPPORT.roles                    =CN=sm-eprndw-csradmin
SUPPORT.division                 =060
SUPPORT.location                 =00 00000
SUPPORT.fullname                 =Support Team
SUPPORT.firstname                =Support
SUPPORT.lastname                 =Team
SUPPORT.jobcode                  =12345

USER.roles                       =CN=sm-eprndw-csradmin
USER.division                    =011
USER.location                    =0K 00002
USER.fullname                    =User Team
USER.firstname                   =User
USER.lastname                    =Team
USER.jobcode                     =12345


