#log4j.rootCategory=WARN, stdout
log4j.rootCategory=DEBUG, R,stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - <%m>%n
 
# Enable logging
#log4j.category.com.kroger.javaweb=INFO
# Enable debug logging for your specific package or class
log4j.category.com.kroger.javaweb=DEBUG
log4j.category.com.kroger.pharmacy.csr=DEBUG
logj4.category.org.springframework=DEBUG

log4j.category.org.hibernate.cache=FATAL

# Example with Appender
#log4j.category.com.kroger.javaweb=INFO, exampleappender

#log4j.appender.exampleappender=org.apache.log4j.RollingFileAppender
#log4j.appender.exampleappender.File=/cs/example/AppLogs/example.log
#log4j.appender.exampleappender.MaxFileSize=512KB
#log4j.appender.exampleappender.MaxBackupIndex=3
#log4j.appender.exampleappender.layout=org.apache.log4j.PatternLayout
#log4j.appender.exampleappender.layout.ConversionPattern=%d %p - %m%n
