###############################################################################
## Resource Bundle file for the Stripes Framework. Values should be
## placed in here for the following:
##   - Form Field Labels, unless you want users to see a non-localized, non-
##     pretty name from the form field declaration (prettied up a little).
##   - Error messages for:
##       - Standard validation error messages
##       - Converter error messages
##       - Error messages used in your custom ActionBean classes
###############################################################################

# Resource strings used by the stripes:errors tag when there are no nested tags
stripes.errors.validationFailed=Please correct the fields shown in red below.
stripes.errors.header=<ol>
stripes.errors.beforeError=<li style="color: #b72222;">
stripes.errors.afterError=</li>
stripes.errors.footer=</ol>

stripes.fieldErrors.header=
stripes.fieldErrors.beforeError=<span style="color: #b72222;">
stripes.fieldErrors.afterError=</span>
stripes.fieldErrors.footer=

# Resource strings used by the stripes:messages tag
stripes.messages.header=<ul class="messages">
stripes.messages.beforeMessage=<li>
stripes.messages.afterMessage=</li>
stripes.messages.footer=</ul>

# Validation error messages produced by converter classes
converter.number.invalidNumber=The value ({1}) entered in field {0} must be a valid number
converter.byte.outOfRange=The value ({1}) entered in field {0} was out of the range {2} to {3}
converter.short.outOfRange=The value ({1}) entered in field {0} was out of the range {2} to {3}
converter.integer.outOfRange=The value ({1}) entered in field {0} was out of the range {2} to {3}
converter.float.outOfRange=The value ({1}) entered in field {0} was out of the range {2} to {3}
converter.enum.notAnEnumeratedValue=The value "{1}" is not a valid value for field {0}
converter.date.invalidDate=The value ({1}) entered in field {0} must be a valid date
converter.email.invalidEmail=The value ({1}) entered is not a valid email address

converter.dateRange.invalidEncoding=The value ({0}) entered is not a date range.
converter.familytree.invalidEncoding=The value ({0}) entered is not a product classification.

# Validation error messages produced by the annotation based validations
validation.required.valueNotPresent={0} is a required field
validation.minlength.valueTooShort={0} must be at least {2} characters long
validation.maxlength.valueTooLong={0} must be no more than {2} characters long
validation.minvalue.valueBelowMinimum=The minimum allowed value for {0} is {2}
validation.maxvalue.valueAboveMaximum=The maximum allowed value for {0} is {2}
validation.mask.valueDoesNotMatch=<em>{1}</em> is not a valid value for {0}
validation.expression.valueFailedExpression=The value supplied ({1}) for {0} is invalid

# Example Validation error messages using images
#validation.required.valueNotPresent=<img src="${styleUrl}/default/warning.gif" alt="{0} is a required field"/>

dataAccess.resourceFailureException=The connection to the database has failed
dataAccess.dataSourceLookupFailureException=The database could not be found
dataAccess.cleanupFailureDataAccessException=The update completed, but the cleanup process failed
dataAccess.invalidDataAccessApiUsageException=A bad SQL statement was created by the application
dataAccess.invalidDataAccessResourceUsageException=A bad SQL statement was issued to the database
dataAccess.dataRetrievalFailureException=Expected data could not be found in the database
dataAccess.concurrencyFailureException=A required database lock could not be acquired (deadlock)
dataAccess.permissionDeniedDataAccessException=Permission was denied to access database or table
dataAccess.dataIntegrityViolationException=Update would cause a duplicate row, or delete failed because data is referenced elsewhere
dataAccess.uncategorizedDataAccessException=An uncategorized data access error occurred 
dataAccess.unknownException=An unknown data access error occurred
